name: Trigger Submodule Workflow

on:
  push:
    branches:
      - dev

jobs:
  trigger-submodule-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the submodule.yml workflow in the telliot-feeds repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/fetchoracle/telliot-feeds/actions/workflows/submodule.yml/dispatches \
            -d '{"ref":"main"}'
