name: Test
on:
  push:
    branches: ["dev", "staging", "main", "add-test-workflow"]
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3 
      - name: Set Python version to v3.9
        uses: actions/setup-python@v3.1.4
        with:
            python-version: '${{ matrix.python-version }}'
      - name: Set Node.js version to latest LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements-dev.txt
          pip install -e .
          npm install ganache --global
      - name: Install Node.js dependencies
        run: |
          npm install ganache --global
      - name: Run tests
        run: |
          pytest
